name: setup

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Build
        run: wget https://raw.githubusercontent.com/AnzenKodo/AnzenKodo.github.io/refs/heads/main/README.md

      - name: Save files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save files
